Fixing and synchronizing dumper
BepInEx/HarmonyX pull request #118
Opened 2024-07-24 03:10 UTC by kohanis

2024-12-12 17:01 UTC, ds5678 commented on Harmony/Internal/Util/CecilEmitter.cs
> +	}
Are `clone` and `original` guaranteed to have the same count? If so, add a `Debug.Assert` call. If not, `clone[idx]` is a bug.

Are there actually situations where `clone.Contains(target)` returns true?

I'm uncomfortable with ever returning `target`. I feel like it should throw if the instruction isn't found.

2024-12-12 17:02 UTC, ds5678 commented on Harmony/Internal/Util/CecilEmitter.cs
> +		};
Justification?

2024-12-17 10:55 UTC, Meivyn commented on Harmony/Internal/Util/CecilEmitter.cs
> +				NoInlining = true
Dumps are broken without this when you try to dump a transpiler method that is also postfixed. Same think for relinker below.

2024-12-18 06:50 UTC, Meivyn commented
While it fixed some of the cases I encountered previously, it seems to still be causing issues.

![image](https://github.com/user-attachments/assets/374f06fb-2cec-4ae3-8404-57ff5d03afc5)

2024-12-18 07:03 UTC, ds5678 commented
@Meivyn If you wrote unit tests demonstrating your bug, that would be exceedingly useful and would significantly increase the likelihood that fixes get merged.

2024-12-18 07:15 UTC, Meivyn commented on Harmony/Internal/Util/CecilEmitter.cs
> +		};
https://github.com/MonoMod/MonoMod/blob/26a0a4d22fcd233dd22db4fd034cb3ac41420fd4/src/MonoMod.Utils/DMDGenerators/DMDCecilGenerator.cs#L72-L83

2024-12-18 07:34 UTC, Meivyn commented
It's actually because of `Transpilers.EmitDelegate` here, because passing a static method with `OpCodes.Call` works fine. To write unit tests you must narrow down the issue, and that's not something I was able to achieve with the previous issue. And now it seems that the issue might be in how this helper method is handled.

2024-12-26 21:33 UTC, kohanis commented
Split into commits. Reworked fix a bit. Added a test. Left comments because they are in the original and have a contextual meaning

2024-12-26 22:27 UTC, kohanis commented
CI failed on setup-dotnet, huh)

2025-01-10 20:25 UTC, ds5678 commented on Harmony/Internal/Util/CecilEmitter.cs
> +			}*/
@kohanis

2025-01-10 20:33 UTC, ds5678 requested changes

2025-01-10 20:33 UTC, ds5678 commented on Harmony/Internal/Util/CecilEmitter.cs
> +		*/
Delete

2025-01-10 20:33 UTC, ds5678 commented on Harmony/Internal/Util/CecilEmitter.cs
> +			throw new NullReferenceException($"ILLabel from dump copy of '{originalName}' cannot be relinked. It points to '{target}', which was not found in the original body");
This should be an IndexOutOfRangeException. Nothing here is null.

2025-01-10 20:33 UTC, ds5678 commented on Harmony/Internal/Util/CecilEmitter.cs
> +		foreach (var handler in body.ExceptionHandlers.Where(handler => handler.CatchType != null))
Why switch from `clone.Body` to `body`?

2025-01-10 21:01 UTC, kohanis commented on Harmony/Internal/Util/CecilEmitter.cs
> +		};
Monomod changes

2025-01-10 21:01 UTC, kohanis commented on Harmony/Internal/Util/CecilEmitter.cs
> +				NoInlining = true
Monomod changes

2025-01-10 21:06 UTC, ds5678 approved these changes

2025-01-10 23:10 UTC, ManlyMarco approved these changes

2025-01-10 23:11 UTC, merged